// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLoopDelayMinutesChange();

float dissolved_Oxygen;
float pH;
float total_Dissolved_Solids;
float turbidity;
int loop_Delay_Minutes;
bool comms_OK;
bool sensors_Immersed;
bool system_OK;
CloudTemperature air_Temperature;
CloudTemperature water_Temperature;

void initProperties(){

  ArduinoCloud.addProperty(dissolved_Oxygen, READ,  30 * SECONDS, NULL);
  ArduinoCloud.addProperty(pH, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(total_Dissolved_Solids, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(turbidity, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(loop_Delay_Minutes, READWRITE, 30 * SECONDS, onLoopDelayMinutesChange);
  ArduinoCloud.addProperty(comms_OK, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(sensors_Immersed, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(system_OK, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(air_Temperature, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(water_Temperature, READ, 30 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
